version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/antons
    env_file:
      - .env
    networks:
      - webnet
networks:
  webnet: